version: '3.8'

services:
  frontend:
    build: 
      context: ./code/frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
  backend:
    build: 
      context: ./code/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
      
